-- SupplierOnboarding Database Schema (Generated from schema.cds)
-- This is a PREVIEW of the SQL that would be generated by 'cds deploy'
-- Namespace: supplierOnboarding
-- Database: SQLite (development) / SAP HANA (production)

-- ============================================================================
-- Core Entity: SupplierInvitations
-- ============================================================================
CREATE TABLE SupplierOnboarding_SupplierInvitations (
  -- Primary Key (from cuid aspect)
  ID VARCHAR(36) PRIMARY KEY DEFAULT (uuid()),
  
  -- Managed aspect (timestamps)
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  createdBy VARCHAR(255),
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedBy VARCHAR(255),
  
  -- Supplier contact
  email VARCHAR(255) NOT NULL,
  companyName VARCHAR(255),
  contactName VARCHAR(255),
  
  -- JWT token
  tokenHash VARCHAR(64),
  jwtPayload TEXT,
  
  -- Token lifecycle
  tokenState VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  issuedAt TIMESTAMP NOT NULL,
  expiresAt TIMESTAMP NOT NULL,
  validatedAt TIMESTAMP,
  consumedAt TIMESTAMP,
  revokedAt TIMESTAMP,
  revokedBy VARCHAR(255),
  revocationReason VARCHAR(1000),
  
  -- Email tracking
  emailSentAt TIMESTAMP,
  emailDeliveredAt TIMESTAMP,
  emailOpenedAt TIMESTAMP,
  emailProvider VARCHAR(50) DEFAULT 'SendGrid',
  emailMessageId VARCHAR(255),
  
  -- Rate limiting
  validationAttempts INTEGER DEFAULT 0,
  lastValidationAttempt TIMESTAMP,
  ipAddressFirstAccess VARCHAR(45),
  userAgentFirstAccess VARCHAR(500),
  
  -- ABAC attributes
  departmentCode VARCHAR(50),
  costCenter VARCHAR(50),
  invitedBy VARCHAR(255),
  invitationNotes VARCHAR(2000),
  
  -- Constraints
  CHECK (tokenState IN ('CREATED', 'SENT', 'DELIVERED', 'OPENED', 'VALIDATED', 'CONSUMED', 'FAILED', 'EXPIRED', 'REVOKED'))
);

CREATE INDEX idx_invitations_email ON SupplierOnboarding_SupplierInvitations(email);
CREATE INDEX idx_invitations_tokenHash ON SupplierOnboarding_SupplierInvitations(tokenHash);
CREATE INDEX idx_invitations_state ON SupplierOnboarding_SupplierInvitations(tokenState);
CREATE INDEX idx_invitations_expiresAt ON SupplierOnboarding_SupplierInvitations(expiresAt);

-- ============================================================================
-- Core Entity: SupplierOnboardingData
-- ============================================================================
CREATE TABLE SupplierOnboarding_SupplierOnboardingData (
  -- Primary Key (from cuid aspect)
  ID VARCHAR(36) PRIMARY KEY DEFAULT (uuid()),
  
  -- Managed aspect (timestamps)
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  createdBy VARCHAR(255),
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedBy VARCHAR(255),
  
  -- Foreign Key to invitation
  invitation_ID VARCHAR(36) NOT NULL,
  
  -- Company information
  companyLegalName VARCHAR(255) NOT NULL,
  taxId VARCHAR(50),
  vatNumber VARCHAR(50),
  dunsNumber VARCHAR(20),
  businessRegistration VARCHAR(100),
  
  -- Contact details
  street VARCHAR(255),
  city VARCHAR(100),
  region VARCHAR(100),
  postalCode VARCHAR(20),
  country_code VARCHAR(3),  -- FK to common.Countries
  
  primaryContactName VARCHAR(255),
  primaryContactEmail VARCHAR(255),
  primaryContactPhone VARCHAR(50),
  
  -- Banking information
  bankName VARCHAR(255),
  bankAccountNumber VARCHAR(100),  -- Should be encrypted in production
  bankRoutingNumber VARCHAR(50),
  swiftCode VARCHAR(20),
  iban VARCHAR(50),
  
  -- Business details
  yearEstablished INTEGER,
  numberOfEmployees INTEGER,
  annualRevenue DECIMAL(15,2),
  currency_code VARCHAR(3),  -- FK to common.Currencies
  websiteUrl VARCHAR(500),
  businessDescription VARCHAR(2000),
  
  -- Industry
  industryCode VARCHAR(20),
  commodities VARCHAR(1000),
  
  -- Payment terms
  preferredPaymentTerms VARCHAR(100),
  preferredCurrency_code VARCHAR(3),
  
  -- Status tracking
  onboardingStatus VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  submittedAt TIMESTAMP,
  reviewedAt TIMESTAMP,
  reviewedBy VARCHAR(255),
  reviewNotes VARCHAR(2000),
  approvalDate TIMESTAMP,
  approvedBy VARCHAR(255),
  
  -- S/4HANA integration
  s4BusinessPartnerId VARCHAR(50),
  s4VendorId VARCHAR(50),
  s4SyncedAt TIMESTAMP,
  s4SyncStatus VARCHAR(50),
  s4SyncErrors TEXT,
  
  -- Foreign key constraint
  FOREIGN KEY (invitation_ID) REFERENCES SupplierOnboarding_SupplierInvitations(ID),
  
  -- Constraints
  CHECK (onboardingStatus IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'SYNCED_TO_S4', 'REJECTED', 'ADDITIONAL_INFO'))
);

CREATE INDEX idx_onboarding_invitation ON SupplierOnboarding_SupplierOnboardingData(invitation_ID);
CREATE INDEX idx_onboarding_status ON SupplierOnboarding_SupplierOnboardingData(onboardingStatus);
CREATE INDEX idx_onboarding_s4bp ON SupplierOnboarding_SupplierOnboardingData(s4BusinessPartnerId);

-- ============================================================================
-- Composition Entity: AttachmentMetadata
-- ============================================================================
CREATE TABLE SupplierOnboarding_AttachmentMetadata (
  -- Primary Key (from cuid aspect)
  ID VARCHAR(36) PRIMARY KEY DEFAULT (uuid()),
  
  -- Managed aspect (timestamps)
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  createdBy VARCHAR(255),
  modifiedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modifiedBy VARCHAR(255),
  
  -- Parent relationship (composition)
  onboardingData_ID VARCHAR(36) NOT NULL,
  
  -- File metadata
  fileName VARCHAR(255) NOT NULL,
  fileSize INTEGER,
  mimeType VARCHAR(100),
  attachmentType VARCHAR(30) NOT NULL,
  description VARCHAR(500),
  
  -- Object Store reference
  storageKey VARCHAR(500) NOT NULL,
  bucketName VARCHAR(100) DEFAULT 'onboarding-documents',
  storageRegion VARCHAR(50),
  
  -- Security
  uploadedBy VARCHAR(255),
  virusScanStatus VARCHAR(20),
  virusScanDate TIMESTAMP,
  
  -- Access control
  expiryDate TIMESTAMP,
  isArchived BOOLEAN DEFAULT 0,
  archivedAt TIMESTAMP,
  
  -- Foreign key constraint with cascading delete
  FOREIGN KEY (onboardingData_ID) REFERENCES SupplierOnboarding_SupplierOnboardingData(ID) ON DELETE CASCADE,
  
  -- Constraints
  CHECK (attachmentType IN ('TAX_CERTIFICATE', 'BUSINESS_LICENSE', 'BANK_DETAILS', 'COMPANY_REGISTRATION', 'ISO_CERTIFICATE', 'OTHER_DOCUMENT'))
);

CREATE INDEX idx_attachments_onboarding ON SupplierOnboarding_AttachmentMetadata(onboardingData_ID);
CREATE INDEX idx_attachments_type ON SupplierOnboarding_AttachmentMetadata(attachmentType);

-- ============================================================================
-- Audit Entity: AuditLogs
-- ============================================================================
CREATE TABLE SupplierOnboarding_AuditLogs (
  -- Primary Key (from cuid aspect)
  ID VARCHAR(36) PRIMARY KEY DEFAULT (uuid()),
  
  -- Immutable timestamp (not using managed aspect)
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  -- Event classification
  eventType VARCHAR(50) NOT NULL,
  eventCategory VARCHAR(50),
  severity VARCHAR(20),
  
  -- Context (optional FKs)
  invitation_ID VARCHAR(36),
  onboardingData_ID VARCHAR(36),
  
  -- Actor
  actorId VARCHAR(255),
  actorEmail VARCHAR(255),
  actorRole VARCHAR(100),
  
  -- Technical details
  ipAddress VARCHAR(45),
  userAgent VARCHAR(500),
  sessionId VARCHAR(100),
  correlationId VARCHAR(100),
  
  -- Event data
  eventDescription VARCHAR(2000) NOT NULL,
  oldValue TEXT,
  newValue TEXT,
  errorMessage VARCHAR(2000),
  stackTrace TEXT,
  
  -- Compliance flags
  isPII BOOLEAN DEFAULT 0,
  isFinancial BOOLEAN DEFAULT 0,
  requiresNotification BOOLEAN DEFAULT 0,
  
  -- Data retention
  retentionPeriodDays INTEGER DEFAULT 2555,  -- 7 years
  archiveAfter TIMESTAMP,
  
  -- Foreign key constraints (optional references)
  FOREIGN KEY (invitation_ID) REFERENCES SupplierOnboarding_SupplierInvitations(ID),
  FOREIGN KEY (onboardingData_ID) REFERENCES SupplierOnboarding_SupplierOnboardingData(ID),
  
  -- Constraints
  CHECK (eventType IN ('INVITATION_CREATED', 'TOKEN_SENT', 'TOKEN_VALIDATED', 'ONBOARDING_STARTED', 'DATA_SUBMITTED', 'DOCUMENT_UPLOADED', 'STATUS_CHANGED', 'ADMIN_ACTION', 'S4_SYNC_SUCCESS', 'S4_SYNC_FAILURE', 'TOKEN_EXPIRED', 'TOKEN_REVOKED'))
);

CREATE INDEX idx_audit_timestamp ON SupplierOnboarding_AuditLogs(timestamp);
CREATE INDEX idx_audit_eventType ON SupplierOnboarding_AuditLogs(eventType);
CREATE INDEX idx_audit_invitation ON SupplierOnboarding_AuditLogs(invitation_ID);
CREATE INDEX idx_audit_onboarding ON SupplierOnboarding_AuditLogs(onboardingData_ID);
CREATE INDEX idx_audit_correlationId ON SupplierOnboarding_AuditLogs(correlationId);

-- ============================================================================
-- Summary
-- ============================================================================
-- Tables created: 4
-- Indexes created: 14
-- Referential integrity: Enforced with foreign keys
-- Cascading delete: AttachmentMetadata ON DELETE CASCADE
-- Enumerations: Enforced with CHECK constraints
